name: Deploy Laravel Application

on:
  push:
    branches:
      - main # Specify the branch to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }} # Your server's IP
          username: ${{ secrets.SERVER_USER }} # Your SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your private SSH key
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # The passphrase for the private key
          port: ${{ secrets.SSH_PORT }} # Your SSH port (default is 22)
          source: "." # Copy everything in the root of the repository
          target: "/www/panel" # Your Laravel directory on the server

      - name: SSH and configure environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }} # Your server's IP
          username: ${{ secrets.SERVER_USER }} # Your SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your private SSH key
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # The passphrase for the private key
          port: ${{ secrets.SSH_PORT }} # Your SSH port (default is 22)
          script: |
            cd /www/panel  # Move to the Laravel directory

            # Create or update .env file
            cp .env.example .env
            echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

            # Install dependencies
            composer install --no-dev --optimize-autoloader --ignore-platform-reqs

            # Run migrations
            php artisan migrate --force
